### PR TITLE
saving my eyeballs

### PR DESCRIPTION
**Pull request by Xe-Xo**
split the user name by new line so we dont have crazy ascii covering the screen

### CODE REVIEW

**Comment by PWhiddy** [comment]
I do actually think its kinda fun to be able to make a larger block of text if you want to, although it definitely would be nice to disable it. Maybe we could add a toggle / checkbox in the corner for this option maybe? Ideally we could list all the people currently broadcasting and generate a toggle for each individually. Do you think any of this is possible?

**Comment by Xe-Xo** [comment]
image

added an input box to the html page.
updated the startAnimationForPath function to see if the username matches the input box value.
sets the fontsize to 128.
removed any non-alphanumeric characters from the username.

**Comment by Xe-Xo** [comment]
this should serve for now.
i removed the username validation and just included a checkbox to see only the agent name if you wish.

**Comment by PWhiddy** [comment]
thanks! going to merge this for now and hope nothing breaks 🤞

**Comment by xinpw8** [comment]
Nice. Something good came out of my ascii experiment!

**Pull request merged**
